version: '3.8'

services:
  react-app:
    build: .
    container_name: tanstack-app-container
    ports:
      - "3000:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # For Hot Reload
      - WATCHPACK_POLLING=true    # Additional for Vite/Webpack
    # Override the command to make Vite listen for external requests
    command: npm run dev -- --host
    stdin_open: true
    tty: true
