import createClient, { type Middleware } from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

export const baseUrl = 'https://musicfun.it-incubator.app/api/1.0'


const myMiddleware: Middleware = {
  async onRequest({ request }) {
    const accessToken = localStorage.getItem('musicfun-access-token')

    if (accessToken) {
      request.headers.set("Authorization", "Bearer " + accessToken);
    }

    return request;
  },
  async onResponse({ response }) {
    if (!response.ok) {
      throw new Error(`${response.url}: ${response.status} ${response.statusText}`)
    }
  },
};

export const client = createClient<paths>({ baseUrl, headers: {
  'api-key': import.meta.env.VITE_API_KEY}
});

// register middleware
client.use(myMiddleware);
